### ISSUE TITLE
Comment style

### ISSUE THREAD

**Issue by wejick** [regalius/clean-arch#2]
https://github.com/regalius/clean-arch/blob/c92f4ea1d09ebcaea6a0cfc8590e878af41bef23/sample-app/pkg/model/shop/type.go#L6

Because this will be used as example, I expect the comment style use common godoc commenting style.

No need `:`
https://blog.golang.org/godoc-documenting-go-code

and for my personal taste, no need to `sectionize` code with comment
```
// start model
...
// end model
```

Better struct naming is enough

**Comment by regalius** [comment]
Changed as of now, no more colons, closing this for now
