### ISSUE TITLE
More clear but still consise variable naming

### ISSUE THREAD

**Issue by wejick** [regalius/clean-arch#3]
https://github.com/regalius/clean-arch/blob/c92f4ea1d09ebcaea6a0cfc8590e878af41bef23/sample-app/pkg/model/shop/type.go#L29

because this will be example I would suggest having clear but still concise variable naming :
`lt` = lessThan, `gt` = greaterThan?
I'm not sure what that means actually

**Comment by regalius** [comment]
Changed, closing for now
