### ISSUE TITLE
Struct memory alignment

### ISSUE THREAD

**Issue by wejick** [regalius/clean-arch#6]
https://github.com/regalius/clean-arch/blob/c92f4ea1d09ebcaea6a0cfc8590e878af41bef23/sample-app/pkg/model/product/type.go#L7

because this will be example, I would like to have good example of aligned struct.

good reading :
https://dave.cheney.net/2015/10/09/padding-is-hard
https://medium.com/@felipedutratine/how-to-organize-the-go-struct-in-order-to-save-memory-c78afcf59ec2

**Comment by regalius** [comment]
Done, closing for now
